Sprint 3
DmitryLavrov/middle.messenger.praktikum.yandex pull request #13
Opened 2022-11-27 16:42 UTC by DmitryLavrov

2022-11-28 03:10 UTC, maks88sgt requested changes
Привет. Отличная работа. У тебя хорошо получилась разбивка на модули и работа с TS. Есть несколько моментов, которые нужно поправить, чтобы идти дальше:
1. Переработать код сервера. Сейчас сервер может отправлять только index страницу и не знает о других запросах. Это приводит к тому, что по прямой ссылке или при перезагрузке страницы происходит ошибка.
2. При отрисовке сообщений полученных по вебсокетам неправильная сортировка (все сообщения отрисовываются как принадлежащие юзеру). После перезагрузки отрисовывается правильно.
3. Удалить закомментированный код
4. Также есть предложение переработать код модулей контроллеров и модулей взаимодействующих с апи. Давай попробуем избавиться от большой вложенности if/else используя try/catch с одним обработчиком catch и попробуем вместо длинных цепочек промисов использовать async/await. Код должен получиться легко читаемым и поддерживаемым. 
Если будут вопросы пиши комментарии

2022-11-28 10:05 UTC, DmitryLavrov commented on src/components/messenger/chatsBox/chatBoxEventHandlers.ts
> +          // router.go('/messenger')
Закомментированный код убрал.

2022-11-28 16:38 UTC, DmitryLavrov commented on src/components/messenger/currentChat/currentChatEventHandlers.ts
> +}
Все eventHangler переписал на async/await

2022-11-28 16:39 UTC, DmitryLavrov commented on src/core/block.ts
>    // constructor
Тут не понял, о чем речь. Просьба пояснить.

2022-11-29 02:37 UTC, maks88sgt approved these changes
Работу принял. Успехов на курсе

2022-11-29 07:01 UTC, merged